name: ILP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    name: ILP To EXE
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with Pyinstaller
        run: |
          pyinstaller -Fw ./ILP.py
      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ILP
          path: dist
          
          

            
